# Always pair ipynb notebooks to md files
formats = "ipynb,md:myst"

# Don't store run_control metadata
cell_metadata_filter = "-run_control,-deletable,-editable,-jupyter,-slideshow"
notebook_metadata_filter="-jupytext.cell_metadata_filter,-jupytext.notebook_metadata_filter"
