title = "Python for GIS and Geoscience"
organisation = "Doctoral schools of Ghent University"
dates = "November 21, 23 and 25, 2022"
repository = "DS-python-geospatial"
conda_environment = "DS-geospatial"
hackmd = "https://hackmd.io/MsRlxUUqQVKtyt_dNoInBg?both"
googleform = "https://forms.gle/wYwY37f6z9j7J5iP8"